server:
  port: 8002
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
spring:
  application:
    name: huaapi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
#       这个路由使用配置类配置自定义拦截器，用配置文件不知道怎么回事总是找不到 Bean
#        - id: huaapi-interface
#          uri: lb://huaapi-interface
#          predicates:
#            - Path=/api/interface/**
#          filters:
#            - interfaceFilter
        - id: huaapi-order
          uri: lb://huaapi-order
          predicates:
            - Path=/api/order/**
        - id: huaapi-third
          uri: lb://huaapi-third
          predicates:
            - Path=/api/third/**
        - id: huaapi-backend
          uri: lb://huaapi-backend
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: customer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    # 配置namespace
    parameters:
      namespace: 16239c21-ac42-46bc-a4e7-690e64272f5a